Prevent error on startup if the site hasn't been built before.
See https://devopsdays.slack.com/archives/C07T0BHHN/p1597278391092100 -
Hugo doesn't start up if your shell isn't bash and you don't have
some directories present in the repository with specific permissions.

```
[don@zeus ~/devopsdays-web:master] ./hugoserver.sh
hugo-server
hugo-server
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /home/circleci/project/resources/_gen: permission denied
[don@zeus ~/devopsdays-web:master] mkdir resources/_gen
[don@zeus ~/devopsdays-web:master] ./hugoserver.sh
hugo-server
hugo-server
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /home/circleci/project/resources/_gen/assets: permission denied
[don@zeus ~/devopsdays-web:master] mkdir resources/_gen/assets
[don@zeus ~/devopsdays-web:master] ./hugoserver.sh
hugo-server
hugo-server
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /home/circleci/project/resources/_gen/images: permission denied
[don@zeus ~/devopsdays-web:master] mkdir resources/images
[don@zeus ~/devopsdays-web:master] ./hugoserver.sh
hugo-server
hugo-server
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /home/circleci/project/resources/_gen/images: permission denied
[don@zeus ~/devopsdays-web:master] chmod -R 777 resources
[don@zeus ~/devopsdays-web:master] ./hugoserver.sh
hugo-server
hugo-server

                   |  EN
-------------------+--------
  Pages            |  4464
  Paginator pages  |     2
  Non-page files   |    42
  Static files     | 14733
  Processed images |     0
  Aliases          |   352
  Sitemaps         |     1
  Cleaned          |     0

Built in 31044 ms
Watching for changes in /home/circleci/project/{archetypes,content,data,static,themes}
Watching for config changes in /home/circleci/project/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address )
Press Ctrl+C to stop

```